### ISSUE TITLE
please add custom objects&tab in this source code.

### ISSUE THREAD

**Issue by Amrenders** [rreboucas/sparkle#1]
I try to deploy this repository on my org. Then i got error related to custom objects & tabs. Could you please add custom objects & tab in this source code. Which you are using that's really help full to understand Single page application architecture design.  

 
![capture](https://cloud.githubusercontent.com/assets/20091686/24147336/c0fe8884-0e5f-11e7-90b2-26ef6dcadae1.PNG)

**Comment by rreboucas** [comment]
@Amrenders thanks for letting me know I have just added Custom Objects and Custom Tabs metadata do the repository. Please let me know if you have any issues. Tks!
